### ISSUE TITLE
Hardware Serial

### ISSUE THREAD

**Issue by kasperkamperman** [Seeed-Shield/WiFi_Shield#3]
Hi,

Nice and small library. However you only support SoftSerial. I would like to be able to connect the WiFly to my hardware serial (I know I can't debug then with usb). 

Besides that with a Leonardo you have Serial (that's for USB) and Serial1 (that's RX/TX pin 0/1). It would be nice to use them as well. 

I tried myself to implement hardwareserial (worked on that the past 3 hours), but I can't seem to manage it (I'm a beginner in c++). 
http://arduino.cc/forum/index.php/topic,41665.0.html

Is it not possible to pass the Serial port you would like to use? 
So or a hardware serial of your choice or a software serial port. 
I think the Stream class supports something like that. 

I've tried to implement proxySerial:
http://embeddedcomputing.weebly.com/serial-ports.html
https://github.com/sebgiroux/Serial_LCD/blob/master/proxySerial.h
https://github.com/sebgiroux/Serial_LCD/blob/master/Serial_LCD.h
https://github.com/sebgiroux/Serial_LCD/blob/master/Serial_LCD.cpp

However then the methods from SoftwareSerial don't exist anymore:
wifly_ap:63: error: 'class WiFly' has no member named 'available'
wifly_ap:64: error: 'class WiFly' has no member named 'write'
wifly_ap:64: error: 'class WiFly' has no member named 'read'

Hope you can help.
Thank you in advance. 

Kasper

**Comment by kasperkamperman** [comment]
I just checked. The WiFlyHQ uses this system (where you can use every serial port: 
https://github.com/harlequin-tech/WiFlyHQ

I tried to port parts of that code. But I get stuck with virtual functions and other errors I don't get. 

I like your library better, because it's smaller and with sendCommand you can use all the WiFly commands.

**Comment by xiongyihui** [comment]
Hi kas, I just create a new branch --- dev to make WiFly inherit Stream instread of SoftwareSerial. I don't test the new code yet. To use leonardo's hardware serial, modify the example wifly_test:

```
WiFly wifly(&uart);   ----------------->    WiFly wifly(&Serial1);
uart.begin(9600);     ----------------->    Serial1.begin(9600);
```

**Comment by kasperkamperman** [comment]
Thank you for the super fast response and new version. It works perfect. 

This is what I modified for the Leonardo (it continues only with the setup if you open the serial monitor). 

WiFly wifly(&Serial1);

void setup() {
  Serial1.begin(9600);  // rx/tx WiFly
  Serial.begin(9600);   // debuging serial usb

  while (!Serial) {
    ; // wait for serial port to connect. Needed for Leonardo only
  }
