### ISSUE TITLE
reboot bug

### ISSUE THREAD

**Issue by kasperkamperman** [Seeed-Shield/WiFi_Shield#4]
In wifly.cpp

This:
boolean WiFly::reboot()
{  return sendCommand("reboot\r"); 
}

Should become something like this:
boolean WiFly::reboot()
{  sendCommand("reboot\r"); // first this
   command_mode = false;    // then this
   return true;
}

Since the WiFly goes out of command_mode when rebooting, while the script still things it it's in command mode because that boolean is still true. 

I had some issues with this when because I'm rebooting more times (to create modes) in one Sketch. 

Changing the above code, solved this problem for me.

There are more commands that could give a problem:
run web_app for example, this also reboots.

**Comment by xiongyihui** [comment]
Yes, it's a bug. Thanks.
You can send pull requests to help improving this library.

**Comment by kasperkamperman** [comment]
I'm not so experienced with Github, so I'll do it in this way for now.
